# Generated by Django 4.0.5 on 2022-07-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='короткий опис'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='заголовок'),
        ),
    ]
