# Generated by Django 4.0.5 on 2022-07-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuko', '0003_mainpage_text_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='text_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='картка 1'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='text_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='картка 1'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='text_4',
            field=models.CharField(blank=True, max_length=200, verbose_name='картка 1'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='text_5',
            field=models.CharField(blank=True, max_length=200, verbose_name='картка 1'),
        ),
    ]
